# General settings
name: 'null6126'
description: 'the default theme for null6126.de'
title: 'here should be a title, but there is none'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
repository: 'https://github.com/philippsiegmund/null6126-jekyll-theme'
email: 'hello-dev@null6126.de'
author:
  name: 'psgmnd'
  url: 'https://psgmnd.de'
  email: 'null6126@psgmnd.de'

baseurl: ''
include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Default scope for posts and pages
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]